
{ pkgs, ... }:
{
users.users."maddie" = {
  description = "Madeline";
  isNormalUser = true;
  shell = pkgs.fish;
  openssh.authorizedKeys.keys = [
    "sk-ecdsa-sha2-nistp256@openssh.com AAAAInNrLWVjZHNhLXNoYTItbmlzdHAyNTZAb3BlbnNzaC5jb20AAAAIbmlzdHAyNTYAAABBBHPDuIYymodbRyNLyBj2lhyzkmoZDgQRmEdmAItCWa5+jMis5tw1c5wmZaFARr/RouHn12WkybbMSWlCOnRwLRcAAAAEc3NoOg== Solokey" 
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGB3X4E2F2+o5VA1pdTuMDOXPF8YNGPXUOFaXXOjy9US Generated By Termius" 
    "sk-ecdsa-sha2-nistp256@openssh.com AAAAInNrLWVjZHNhLXNoYTItbmlzdHAyNTZAb3BlbnNzaC5jb20AAAAIbmlzdHAyNTYAAABBBCGKwlVdRuihYWgT1itujm8d3cqU9evzxjh/qifEh04owqvWrjM/P1EcAa9CyCLJ/Dm/3Tl/MiieF5sLB1EdUigAAAAEc3NoOg== swl@Sakuta"
    "sk-ecdsa-sha2-nistp256@openssh.com AAAAInNrLWVjZHNhLXNoYTItbmlzdHAyNTZAb3BlbnNzaC5jb20AAAAIbmlzdHAyNTYAAABBBBdfLBcsv4rohr2ejZtFgpT0I5o88nbYC8r/EgrptwjMExll4CRlvFLTn1FZK+MdKoHgYdnPoQqn9Qei450EUhUAAAAEc3NoOg== ellie@Sakuta"

  ];
  extraGroups = [ "wheel" "tty" ];
};
}
